# File: .github/workflows/cd.yml

name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

      - name: Deploy
        env:
          DB_NAME: "db.sqlite3"
          DB_PATH: "./"
          SECRET_KEY: "your_secret_key"
          DJANGO_SETTINGS_MODULE: "your_django_project.settings.production"
        run: |
          python manage.py collectstatic --noinput
          python manage.py migrate --noinput
          python manage.py runserver
